{
  throw new IOException("Test failure");
}
