{
  try {
    return stash.get().compute();
  }
 catch (  Exception e) {
    throw U.withCause(new InvalidObjectException(e.getMessage()),e);
  }
 finally {
    stash.remove();
  }
}
