{
  Throwable err=assertThrowsInherited(log,new Callable(){
    @Override public Object call() throws Exception {
      mgr.move(fileId,srcFileName,srcParentId,destFileName,destParentId);
      return null;
    }
  }
,IgniteCheckedException.class,msg);
  assertTrue("Unexpected cause: " + err.getCause(),err.getCause() instanceof IgniteFsException);
}
