{
  try {
    t.get();
  }
 catch (  IgniteTxOptimisticException ignore) {
    if (log.isDebugEnabled())     log.debug("Optimistic failure while committing prepared transaction (will rollback): " + tx);
    tx.rollbackAsync();
  }
catch (  IgniteCheckedException e) {
    U.error(log,"Failed to commit transaction during failover: " + tx,e);
  }
}
