{
  Throwable err=assertThrowsInherited(log,new Callable(){
    @Override public Object call() throws Exception {
      mgr.move(new IgfsPath(src),new IgfsPath(dst));
      return null;
    }
  }
,IgfsException.class,msg);
  assertTrue("Unexpected cause: " + err,err instanceof IgfsException);
}
