{
  return new CI1<IgniteInternalFuture<?>>(){
    @Override public void apply(    IgniteInternalFuture<?> f){
      try {
        f.get();
      }
 catch (      IgniteCheckedException e) {
        if (!F.isEmpty(excl))         for (        Class cls : excl)         if (e.hasCause(cls))         return;
        U.error(log,"Future execution resulted in error: " + f,e);
      }
    }
    @Override public String toString(){
      return "Error logger [excludes=" + Arrays.toString(excl) + ']';
    }
  }
;
}
