{
  assertNotNull(cfg);
  assertNotNull(excMsgSnippet);
  try {
    G.start(cfg);
    fail("No exception has been thrown.");
  }
 catch (  IgniteCheckedException e) {
    if (testLoc) {
      if ("Failed to start processor: GridProcessorAdapter []".equals(e.getMessage()) && e.getCause().getMessage().contains(excMsgSnippet))       return;
    }
 else     if (e.getMessage().contains(excMsgSnippet))     return;
    error("Caught unexpected exception.",e);
    fail();
  }
}
