{
  try {
    assertNotNull("Null old value: " + entry,entry.getValue());
    assertEquals("Unexpected old value: " + entry,entry.getKey(),entry.getValue());
  }
 catch (  Throwable t) {
    failed=true;
    System.out.println("Unexpected error: " + t);
    t.printStackTrace(System.out);
  }
  return new T2<>(true,null);
}
