{
  assertThrows(log,new Callable<Object>(){
    @Override public Object call() throws Exception {
      data.cas(null,"val1","val2");
      return null;
    }
  }
,NullPointerException.class,"Ouch! Argument cannot be null: key");
}
