{
  try {
    fut.cancel();
  }
 catch (  IgniteCheckedException e) {
    U.error(log,"Failed to cancel task: " + fut,e);
  }
  return true;
}
