{
  assertThrows(log,new Callable<Object>(){
    @Override public Object call() throws Exception {
      data.put(null,"val");
      return null;
    }
  }
,NullPointerException.class,"Ouch! Argument cannot be null: key");
  assertThrows(log,new Callable<Object>(){
    @Override public Object call() throws Exception {
      data.put("key",null);
      return null;
    }
  }
,NullPointerException.class,"Ouch! Argument cannot be null: val");
}
